### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by acrigney** [Azure/GPT-RAG#97]
Sorry guys I have not used bicep before.
I got this error on trying to deploy and then it just hangs
PS F:\gptrag> azd up --debug
azd : 2024/01/31 11:22:01 main.go:54: azd version: 1.5.1 (commit 3856d1e98281683b8d112e222c0a7c7b3e148e96)
At line:1 char:1
+ azd up --debug
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (2024/01/31 11:2...0a7c7b3e148e96):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
2024/01/31 11:22:01 main.go:208: using cached latest version: 1.5.1 (expires on: 2024-01-31T00:45:16Z)
2024/01/31 11:22:01 project.go:113: Reading project from file 'F:\gptrag\azure.yaml'
2024/01/31 11:22:01 user_config_manager.go:39: creating empty config since 'C:\Users\Alistair C Rigney\.azd\config.json' did not 
exist.
2024/01/31 11:22:01 user_config_manager.go:39: creating empty config since 'C:\Users\Alistair C Rigney\.azd\config.json' did not 
exist.

**Comment by acrigney** [comment]
Sorry guys I was using powershell before but it works using VS2022 developer console. 
I had to change to nodejs version 11.15.0 as the latest version 20.11.0 was not accepted.
But I have a new error
0 info it worked if it ends with ok
1 verbose cli [ 'F:\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Alistair C Rigney\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v11.15.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle frontend@0.0.0~prebuild: frontend@0.0.0
6 info lifecycle frontend@0.0.0~build: frontend@0.0.0
7 verbose lifecycle frontend@0.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle frontend@0.0.0~build: PATH: C:\Users\Alistair C Rigney\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\gptrag\.azure\gpt-rag-frontend\frontend\node_modules\.bin;F:\PowerShell\7;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\DiagnosticsHub\Collector;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\\x86;C:\Program Files (x86)\Windows Kits\10\bin\\x86;C:\Program Files\Microsoft Visual Studio\2022\Community\\MSBuild\Current\Bin\amd64;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\Program Files\Microsoft MPI\Bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Users\Alistair C Rigney\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\WINDOWS\System32\OpenSSH\;C:\Microsoft VS Code\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Projects\w64;C:\Projects\pytocs-master\pytocs-master\src\Cli\bin\Debug\net471;C:\Program Files\CMake\bin;C:\Program Files\SourceGear\Common\DiffMerge\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files (x86)\IDEMIA\AWP\Dlls;C:\Program Files\IDEMIA\AWP\Dlls;C:\Program Files\Microsoft\Azure Functions Core Tools\;C:\Program Files\Git\cmd;F:\PowerShell\7\;F:\nodejs\;C:\Users\Alistair C Rigney\AppData\Roaming\.dotnet;C:\Users\Alistair C Rigney\AppData\Local\Microsoft\WindowsApps;C:\Users\Alistair C Rigney\AppData\Local\.meteor\;C:\Users\Alistair C Rigney\AppData\Local\GitHubDesktop\bin;C:\Projects\neo-compiler-master\neo-compiler-master\neon\bin\Release\netcoreapp1.0\win10-x64;C:\Users\Alistair C Rigney\.dotnet\tools;C:\Users\Alistair C Rigney\AppData\Local\Microsoft\WindowsApps;C:\Anaconda3\Scripts;C:\Anaconda3;c:\Program Files\CMake\bin;d:\Fiddler;C:\Users\Alistair C Rigney\.dotnet\tools;C:\Users\Alistair C Rigney\AppData\Local\Programs\Azure Dev CLI\;C:\Users\Alistair C Rigney\AppData\Roaming\npm;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
9 verbose lifecycle frontend@0.0.0~build: CWD: F:\gptrag\.azure\gpt-rag-frontend\frontend
10 silly lifecycle frontend@0.0.0~build: Args: [ '/d /s /c', 'tsc && vite build' ]
11 silly lifecycle frontend@0.0.0~build: Returned: code: 1  signal: null
12 info lifecycle frontend@0.0.0~build: Failed to exec build script
13 verbose stack Error: frontend@0.0.0 build: `tsc && vite build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Alistair C Rigney\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Alistair C Rigney\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:999:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid frontend@0.0.0
15 verbose cwd F:\gptrag\.azure\gpt-rag-frontend\frontend
16 verbose Windows_NT 10.0.18362
17 verbose argv "F:\\nodejs\\node.exe" "C:\\Users\\Alistair C Rigney\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v11.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error frontend@0.0.0 build: `tsc && vite build`
22 error Exit status 1
23 error Failed at the frontend@0.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by acrigney** [comment]
[gptraglog.txt](https://github.com/Azure/GPT-RAG/files/14105979/gptraglog.txt)
This is the complete log from stdout

**Comment by gbecerra1982** [comment]
Hi @acrigney I would like to share that based on the errors we suggest to install the following pre-requisites:

https://github.com/Azure/gpt-rag?tab=readme-ov-file#getting-started

We saw that the issue is related with the node version for the Frontend, GPT-RAG is nodejs 16+ required. We suggest to install all the listed prerequisites and let us know if you were able to solve.

**Comment by placerda** [comment]
We're closing older issues as part of repo maintenance. Feel free to reopen if needed.
